/**
 * DPlusPlusExporter Class - Version 52 (Full & Final Specification)
 * Format D+++ Visualizer v52 - Step 8: Export & Integration
 * * 【V52 修正・完全統合内容】
 * 1. メソッド名復元: UIController からの呼び出しに合わせ downloadSvg を exportSvg に復元。
 * 2. AI Context Export: Step 7 の診断結果を JSON 化し、AI 指示プロンプトと共に提供。
 * 3. 三段構えフォールバック: クリップボード失敗時の Prompt/Console ダンプを完全実装。
 * 4. C++ 生成の安全性: 状態 ID に "State_" プレフィックスを強制付与し予約語衝突を回避。
 * 5. SVG 出力ガード: 描画未完了状態でのエクスポートに対する存在チェックを強化。
 */
class DPlusPlusExporter {
  /**
   * @param {object} uiController - 統合先の UIController インスタンス
   */
  constructor(uiController) {
    this.ui = uiController;
  }

  /* ========================================================================
     1. AI CONTEXT EXPORT (Section 2.1 / 5.4)
     ======================================================================== */

  /**
   * AI（LLM）がモデルを自律修正するための詳細な構造化データを生成し、提供します。
   * クリップボードへのコピーにおいて三段構えのフォールバックを実行します。
   */
  async exportAIContext() {
    console.log("[Exporter] Generating AI Context JSON...");

    try {
      // 1.1 Step 7 Analyzer から診断データを取得
      if (!this.ui.analyzer) {
        throw new Error("Analyzer instance not found.");
      }
      const analysisData = this.ui.analyzer.exportAnalysisForAI();

      // 1.2 プロンプト構築と構造化データのマージ (SSOT Section 3)
      const aiContext = {
        meta: {
          tool: "Format D+++ Visualizer V52",
          timestamp: new Date().toISOString(),
          context_type: "LLM_REPAIR_KIT"
        },
        instruction: {
          system_prompt: "あなたは状態遷移設計のエキスパートです。提供された診断レポート（diagnostics）に基づき、D+++形式のモデルを修正・最適化してください。",
          format_rules: "修正案は必ず D+++ Markdown Table (A, B, C) 形式で提示してください。"
        },
        payload: analysisData
      };

      const jsonString = JSON.stringify(aiContext, null, 2);

      // 1.3 三段構えのフォールバック・シーケンス (Section 5.4 義務化)
      
      // Tier 1: navigator.clipboard.writeText (標準コピー)
      try {
        await navigator.clipboard.writeText(jsonString);
        this.ui.renderer.showToast("AI Context copied to clipboard!", "success");
        console.log("[Exporter] JSON successfully copied via Clipboard API.");
      } catch (clipboardErr) {
        console.warn("[Exporter] Tier 1 copy failed, falling back to Tier 2.");

        // Tier 2: window.prompt (緊急ダイアログ)
        const userCopy = window.prompt(
          "クリップボードへの書き込みに失敗しました。以下のテキストを手動でコピーしてください (Ctrl+C):",
          jsonString.substring(0, 2000) // ダイアログ制限を考慮
        );

        if (userCopy !== null) {
          this.ui.renderer.showToast("Manual copy prompt displayed.", "info");
        } else {
          // Tier 3: Console Dump (最終手段)
          console.log("--- AI CONTEXT DUMP START ---");
          console.log(jsonString);
          console.log("--- AI CONTEXT DUMP END ---");
          
          window.alert("Export failed. Full JSON context has been dumped to the browser console (F12).");
          this.ui.renderer.showToast("Context dumped to console.", "warn");
        }
      }

      // エクスポート完了後に必要に応じてモーダルも表示
      this.showCodeModal('json', jsonString);

    } catch (e) {
      console.error("[Exporter] AI Context Export failed:", e);
      this.ui.renderer.showToast(`Export failed: ${e.message}`, "error");
    }
  }

  /* ========================================================================
     2. PRODUCTION C++ GENERATION (Section 2.2)
     ======================================================================== */

  /**
   * 状態遷移モデルをプロダクションレベルの C++17 コードに変換します。
   * @param {object} data - パース済みデータ
   * @returns {string} C++ ソースコード
   */
  generateCpp(data) {
    const className = "StateMachine";
    const states = data.states;
    const transitions = data.transitions;

    if (!states || states.length === 0) return "// No states defined.";

    let code = `/**\n * Generated by Format D+++ Visualizer V52\n * Production-ready State Machine Implementation (C++17)\n */\n`;
    code += `#include <iostream>\n#include <string>\n#include <cstdint>\n\n`;

    // 2.1 Enum Class 生成 (予約語回避プレフィックス付き)
    code += `enum class State : uint8_t {\n`;
    states.forEach(s => {
      code += `    ${this._flattenState(s.id)},\n`;
    });
    code += `};\n\n`;

    code += `class ${className} {\n`;
    code += `public:\n`;
    code += `    ${className}() : m_currentState(State::${this._flattenState(states[0].id)}) {\n`;
    code += `        std::cout << "[SM] Initialized at ${states[0].id}" << std::endl;\n`;
    code += `    }\n\n`;

    // 2.2 イベントハンドラ (Switch-Case 構造)
    code += `    void handleEvent(const std::string& event) {\n`;
    code += `        switch (m_currentState) {\n`;

    states.forEach(s => {
      code += `            case State::${this._flattenState(s.id)}:\n`;
      const outgoing = transitions.filter(t => t.source === s.id || t.source === "*");
      
      outgoing.forEach((t, idx) => {
        const condition = idx === 0 ? "if" : "else if";
        const guard = (t.guard && t.guard !== "-") ? ` && checkGuard("${t.guard}")` : "";
        const target = t.target || t.source;

        code += `                ${condition} (event == "${t.trigger}"${guard}) {\n`;
        code += `                    // Action: ${t.action || "none"}\n`;
        
        // Exit アクションの挿入
        if (s.exit && s.exit !== "-") {
          code += `                    onExit${this._flattenState(s.id)}();\n`;
        }

        // 状態遷移の実行
        code += `                    m_currentState = State::${this._flattenState(target)};\n`;
        
        // Entry アクションの挿入
        const targetState = states.find(st => st.id === target);
        if (targetState && targetState.entry && targetState.entry !== "-") {
          code += `                    onEntry${this._flattenState(target)}();\n`;
        }
        code += `                }\n`;
      });
      code += `                break;\n`;
    });

    code += `            default: break;\n`;
    code += `        }\n`;
    code += `    }\n\n`;

    code += `private:\n`;
    code += `    State m_currentState;\n\n`;

    // 2.3 メソッドスタブの生成
    states.forEach(s => {
      if (s.entry && s.entry !== "-") {
        code += `    void onEntry${this._flattenState(s.id)}() { /* D+++: ${s.entry} */ }\n`;
      }
      if (s.exit && s.exit !== "-") {
        code += `    void onExit${this._flattenState(s.id)}() { /* D+++: ${s.exit} */ }\n`;
      }
    });

    code += `\n    bool checkGuard(const std::string& expr) { return true; }\n`;
    code += `};\n`;

    return code;
  }

  /* ========================================================================
     3. SVG EXPORT (Section 2.3 / 5.3)
     ======================================================================== */

  /**
   * UIController からの呼び出し名 exportSvg を復元しました。
   * Mermaid が生成した SVG をシリアライズしてファイル保存します。
   */
  exportSvg() {
    const svgElement = document.querySelector('#diagram svg');
    
    // 3.1 描画状態チェック (Section 5.3 ガード)
    if (!svgElement) {
      console.error("[Exporter] SVG element not ready for export.");
      this.ui.renderer.showToast("SVG diagram not rendered yet.", "error");
      return;
    }

    try {
      const serializer = new XMLSerializer();
      let source = serializer.serializeToString(svgElement);

      // XML 宣言の付与
      if (!source.match(/^<\?xml/)) {
        source = '<?xml version="1.0" standalone="no"?>\r\n' + source;
      }

      // Blob の作成とダウンロード実行
      const blob = new Blob([source], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      
      const downloadLink = document.createElement("a");
      downloadLink.href = url;
      downloadLink.download = `d_plus_plus_model_${Date.now()}.svg`;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
      
      URL.revokeObjectURL(url);
      this.ui.renderer.showToast("SVG image exported successfully.", "success");
    } catch (e) {
      console.error("[Exporter] SVG serialization failed:", e);
      this.ui.renderer.showToast("SVG export failed.", "error");
    }
  }

  /* ========================================================================
     4. MODAL & HELPERS
     ======================================================================== */

  /**
   * 生成されたコード（C++ または JSON）をモーダルに表示します。
   * @param {string} mode - 'cpp' | 'json'
   * @param {string} customContent - 指定がある場合はこれを使用
   */
  showCodeModal(mode = 'cpp', customContent = null) {
    const code = customContent || (mode === 'cpp' ? this.generateCpp(this.ui.data) : "");
    
    const modal = document.getElementById('code-modal');
    const codeArea = document.getElementById('cpp-output');
    
    if (modal && codeArea) {
      codeArea.textContent = code;
      modal.style.display = 'flex';
      console.log(`[Exporter] ${mode.toUpperCase()} content displayed in modal.`);
    } else {
      // フォールバック: コンソール出力
      console.log(`--- [Fallback] ${mode.toUpperCase()} Export ---\n`, code);
    }
  }

  /**
   * 状態 ID (A.B.C) を C++ 識別子 (State_A_B_C) に変換します。
   * プレフィックスを強制することで C++ 予約語（class, if, switch等）との衝突を物理的に防ぎます。
   * @private
   */
  _flattenState(id) {
    if (!id) return "State_UNKNOWN";
    
    // ドットをアンダースコアに置換し、プレフィックスを付与 (Section 5.4)
    let flatId = id.replace(/\./g, '_');
    return "State_" + flatId;
  }
}